version: '3.8'

services:
  postgres:
    image: postgres:15.5
    container_name: postgres_database
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"